# Bash-it
- name: download bash_it
  git:
    repo: 'https://github.com/Bash-it/bash-it/'
    dest: "{{ ansible_env.HOME }}/.bash_it"
    depth: 1
    force: yes
- name: hack bash_it to a different rc file
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bash_it/install.sh"
    regexp: "CONFIG_FILE=.bashrc"
    line: "CONFIG_FILE=.bash_it_rc"
- name: install bash_it
  command: "{{ ansible_env.HOME }}/.bash_it/install.sh -s"
- name: source bash_it
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "source $HOME/.bash_it_rc"

# direnv
- name: setup direnv
  become: yes
  apt:
    name: direnv
    update_cache: yes

- name: source direnv
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: 'eval "$(direnv hook bash)"'

# Setup ~/bin/
- name: create ~/bin dir with scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}"
  with_items:
    - bin

- name: setup ~/bin in $PATH
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=$HOME/bin:$PATH"
