# Emacs
- name: Download Emacs
  git:
    repo: 'git://git.savannah.gnu.org/emacs.git'
    dest: "{{ ansible_env.HOME }}/software/others/emacs"
  register: emacs_git
- name: Emacs autogen.sh
  when: emacs_git.changed
  command: "./autogen.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
- name: Emacs configure
  when: emacs_git.changed
  command: "./configure"
  args:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
- name: Emacs make
  when: emacs_git.changed
  make:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
- name: Emacs install
  when: emacs_git.changed
  become: yes
  make:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
    target: install

# Spacemacs
- name: Spacemacs clone
  git:
    repo: 'https://github.com/syl20bnr/spacemacs.git'
    dest: "{{ ansible_env.HOME }}/.emacs.d"

# .spacemacs
- name: Spacemacs clone
  git:
    repo: 'git@github.com:{{ github }}/.spacemacs.d.git'
    dest: "{{ ansible_env.HOME }}/.spacemacs.d"


# xclip for copying images from clipboard
- name: install xclip
  become: yes
  apt:
    name: xclip
    update_cache: yes
