# Emacs
- name: Download Emacs
  git:
    repo: 'git://git.savannah.gnu.org/emacs.git'
    dest: "{{ ansible_env.HOME }}/software/others/emacs"
    depth: 1
  register: emacs_git
- name: setup src repository
  become: yes
  apt_repository:
    repo: deb-src http://archive.ubuntu.com/ubuntu/ bionic main multiverse universe restricted
    state: present
- name: install build requirements
  become: yes
  command: apt build-dep -y emacs
- name: install build essentials
  become: yes
  command: apt install -y build-essential texinfo libgtk-3-dev libxpm-dev libjpeg-dev libgif-dev libtiff-dev libncurses5-dev
- name: Emacs autogen.sh
  when: emacs_git.changed
  command: "./autogen.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
- name: Emacs configure
  when: emacs_git.changed
  command: "./configure"
  args:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
- name: Emacs make
  when: emacs_git.changed
  make:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
- name: Emacs install
  when: emacs_git.changed
  become: yes
  make:
    chdir: "{{ ansible_env.HOME }}/software/others/emacs/"
    target: install

# Spacemacs
- name: Spacemacs clone
  git:
    repo: 'https://github.com/syl20bnr/spacemacs.git'
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    depth: 1

# .spacemacs
- name: Spacemacs clone
  git:
    repo: 'https://github.com/{{ github }}/.spacemacs.d.git'
    dest: "{{ ansible_env.HOME }}/.spacemacs.d"


# xclip for copying images from clipboard
- name: install xclip
  become: yes
  apt:
    name: xclip
